// Auto-generated by scripts/generate-env.mjs — edit env/.env or Vercel env vars
export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:5067',
  defaultSignupRole: 'analyste',
};
