// Auto-generated by scripts/generate-env.mjs — edit env/.env then restart dev server
export const environment = {
  production: false,
  apiBaseUrl: 'https://projetdev2026.onrender.com',
  defaultSignupRole: 'analyste',
};
