import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const envPath = path.join(root, 'env', '.env');
const examplePath = path.join(root, 'env', '.env.example');
const outPath = path.join(root, 'src', 'environments', 'environment.ts');

function parseEnv(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const idx = trimmed.indexOf('=');
    if (idx === -1) {
      continue;
    }
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed
      .slice(idx + 1)
      .trim()
      .replace(/^["']|["']$/g, '');
    vars[key] = value;
  }
  return vars;
}

if (!fs.existsSync(envPath) && fs.existsSync(examplePath)) {
  fs.copyFileSync(examplePath, envPath);
  console.log('Created env/.env from env/.env.example');
}

const vars = fs.existsSync(envPath)
  ? parseEnv(fs.readFileSync(envPath, 'utf8'))
  : {
      API_BASE_URL: 'https://projetdev2026.onrender.com',
      DEFAULT_SIGNUP_ROLE: 'analyste',
    };

const apiBaseUrl = vars.API_BASE_URL || 'https://projetdev2026.onrender.com';
const defaultSignupRole = vars.DEFAULT_SIGNUP_ROLE || 'analyste';
const production = process.env['NODE_ENV'] === 'production';

const content = `// Auto-generated by scripts/generate-env.mjs — edit env/.env then restart dev server
export const environment = {
  production: ${production},
  apiBaseUrl: '${apiBaseUrl.replace(/'/g, "\\'")}',
  defaultSignupRole: '${defaultSignupRole.replace(/'/g, "\\'")}',
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log(`Environment: API_BASE_URL=${apiBaseUrl}`);
