import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const envPath = path.join(root, 'env', '.env');
const examplePath = path.join(root, 'env', '.env.example');
const outPath = path.join(root, 'src', 'environments', 'environment.ts');

function parseEnv(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const idx = trimmed.indexOf('=');
    if (idx === -1) {
      continue;
    }
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed
      .slice(idx + 1)
      .trim()
      .replace(/^["']|["']$/g, '');
    vars[key] = value;
  }
  return vars;
}

if (!fs.existsSync(envPath) && fs.existsSync(examplePath)) {
  fs.copyFileSync(examplePath, envPath);
  console.log('Created env/.env from env/.env.example');
}

const fileVars = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};

// Vercel / CI env vars take precedence over env/.env (production deploys)
const apiBaseUrl =
  process.env.API_BASE_URL ||
  process.env.VITE_API_BASE_URL ||
  fileVars.API_BASE_URL ||
  'http://localhost:5067';

const defaultSignupRole =
  process.env.DEFAULT_SIGNUP_ROLE ||
  fileVars.DEFAULT_SIGNUP_ROLE ||
  'analyste';

const production =
  process.env.NODE_ENV === 'production' ||
  process.env.VERCEL === '1' ||
  process.env.CI === 'true';

const content = `// Auto-generated by scripts/generate-env.mjs — edit env/.env or Vercel env vars
export const environment = {
  production: ${production},
  apiBaseUrl: '${apiBaseUrl.replace(/'/g, "\\'")}',
  defaultSignupRole: '${defaultSignupRole.replace(/'/g, "\\'")}',
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log(`Environment: production=${production}, API_BASE_URL=${apiBaseUrl}`);
