// <auto-generated />
using AgileAi.Data.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AgileAi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628173500_UserPhotoUrl")]
    partial class UserPhotoUrl
    {
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
        }
    }
}
